version: "3.6"

services:

  backstage:
    build: ./
    container_name: backstage
    restart: always
    ports:
      - 9528:9528
    volumes:
      - .:/app
    command: bash -c "npm run start:dev"